### PR TITLE
Env variables, uri transaction naming, version injection, sourcecode offset 

### PR DESCRIPTION
**Pull request by petermein**
First of great job on both the agent and this Laravel package. We have tested it recently and found some good performance bugs.

I would like to help building out this package so here is my first input. If you want to cherry pick some features or want me to split some up. No problem. 

**Updates**
:rainbow: Added env variables for environments
:rainbow: Added route uri naming, for grouping routes on the route name without parameters
:rainbow: Added contract to determine your own version
:bug: Fixed the offset of the source code, was off by one

### CODE REVIEW

**Comment by philkra** [comment]
@petermein thanks a lot! I'm glad the package was helpful! Thanks for your contribution, I will check it in detail in the coming days.

**Comment by philkra** [comment]
@petermein , I did not forget this PR! I have a newborn at home and that surprisingly reduced my github time :)

**Comment by petermein** [comment]
No problem we have kinda implemented it with a work around, anxiously waiting on the PR ;)

**Comment by philkra** [comment]
Hi @petermein , thanks for your contribution! Please do two more things:
* in the `composer.json` add your name to the contributers
* add `.idea` to `.gitignore` :smile:

**Comment by petermein** [comment]
I missed you reaction, but i see its merged already

**Pull request merged**
