### PR TITLE
feature: allow to be installed with illuminate 8 packages

### PR DESCRIPTION
**Pull request by acfabro-rakuten**

### CODE REVIEW

**Comment by dstepe** [comment]
This package should be considered abandoned. I suggest you move to:

https://github.com/arkaitzgarro/elastic-apm-laravel

**Comment by acfabro-rakuten** [comment]
Thanks, we're quite aware and are in the process of doing so. But for now this is what works for us.

**Comment by dstepe** [comment]
Unfortunately, I think you'll need to use a fork. I haven't heard from the package owner for a while and I only watch the project to direct people to alternatives.

**Comment by acfabro-rakuten** [comment]
Nice of you to do so. Yep, we're using a fork, I just pushed my PR here by mistake. Thanks again!

**Comment by philkra** [comment]
closing as repo is going to be archived.

**Pull request closed without merging**
